apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-crds
spec:
  url: oci://ghcr.io/wiremind/wiremind-helm-charts/cert-manager-crds
  ref:
    semver: "^1.20"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-crds
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager-crds
