apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-crds
spec:
  url: oci://ghcr.io/wiremind/wiremind-helm-charts/gateway-api-crds
  ref:
    semver: "^1.5"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-crds
spec:
  chartRef:
    kind: OCIRepository
    name: gateway-crds
