apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-crds.yaml
  - prometheus-crds.yaml
  - cert-manager-crds.yaml
  - cilium-crds.yaml
  - gateway-crds.yaml
  - envoy-gateway-crds.yaml
  - cnpg-crds.yaml
  - garage-crds.yaml
  - redis-crds.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
    patch: |
      - op: test
        path: /spec/install/crds
        value: Skip
      - op: test
        path: /spec/upgrade/crds
        value: Skip
      - op: add
        path: /spec/install/crds
        value: CreateReplace
      - op: add
        path: /spec/upgrade/crds
        value: CreateReplace
      - op: add
        path: /spec/test
        value:
          enable: false
components:
  - ../utils
