machine:
  install:
    disk: /dev/sda
    wipe: true
  sysctls:
    vm.nr_hugepages: "1024"
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
  files:
    - path: /var/etc/cri/conf.d/20-spegel.part
      op: create
      permissions: 0o444
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
  externalCloudProvider:
    enabled: true
---
apiVersion: v1alpha1
kind: HostnameConfig
$patch: delete
