apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secret-generator
spec:
  url: https://helm.mittwald.de
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: secret-generator
spec:
  chart: kubernetes-secret-generator
  sourceRef:
    kind: HelmRepository
    name: secret-generator
  version: "^3.4"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secret-generator
spec:
  targetNamespace: manager
  chartRef:
    kind: HelmChart
    name: secret-generator
  values:
    installCRDs: false
    secretLength: 64
