apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dbstore
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbstore0
spec:
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dbstore
  local:
    path: /var/mnt/dbstore
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dbworker0
