apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
    - source-watcher
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  kustomize:
    patches:
      - target:
          kind: Deployment
        patch: |
          - op: add
            path: /spec/template/spec/tolerations
            value:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Exists"
                effect: "NoSchedule"
              - key: "node.cloudprovider.kubernetes.io/uninitialized"
                operator: "Exists"
                effect: "NoSchedule"
      - target:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
          name: flux-system
        patch: |
          - op: add
            path: /spec/prune
            value: true
          - op: add
            path: /spec/wait
            value: true
  storage:
    class: proxmox-cache
    size: 64Gi
  sync:
    kind: GitRepository
    url: "https://github.com/chlorodose/homelab.git"
    ref: "refs/heads/main"
    path: "."
