apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          kustomize.toolkit.fluxcd.io/prune: disabled
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
    patch: |
      - op: add
        path: /metadata/namespace
        value: flux-system
      - op: add
        path: /spec/driftDetection
        value:
          mode: enabled
      - op: copy
        path: /spec/releaseName
        from: /metadata/name
      - op: add
        path: /spec/interval
        value: 10m
      - op: add
        path: /spec/timeout
        value: 5m
      - op: add
        path: /spec/test
        value:
          enable: true
      - op: add
        path: /spec/install
        value:
          crds: Skip
          serverSideApply: true
          remediation:
            retries: 5
            remediateLastFailure: true
      - op: add
        path: /spec/upgrade
        value:
          crds: Skip
          serverSideApply: enabled
          cleanupOnFail: true
          remediation:
            retries: 5
            remediateLastFailure: true
      - op: add
        path: /spec/rollback
        value:
          serverSideApply: enabled
          cleanupOnFail: true
      - op: add
        path: /spec/uninstall
        value:
          deletionPropagation: foreground
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
    patch: |
      - op: add
        path: /metadata/namespace
        value: flux-system
      - op: add
        path: /spec/prune
        value: true
      - op: add
        path: /spec/deletionPolicy
        value: WaitForTermination
      - op: add
        path: /spec/interval
        value: 10m
      - op: add
        path: /spec/retryInterval
        value: 5s
      - op: add
        path: /spec/wait
        value: true
      - op: add
        path: /spec/timeout
        value: 5m
  - target:
      group: source.toolkit.fluxcd.io
      kind: OCIRepository
    patch: |
      - op: add
        path: /metadata/namespace
        value: flux-system
      - op: add
        path: /spec/interval
        value: 24h
      - op: add
        path: /spec/timeout
        value: 1m
      - op: add
        path: /spec/layerSelector
        value:
          mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
          operation: extract
  - target:
      group: source.toolkit.fluxcd.io
      kind: HelmRepository
    patch: |
      - op: add
        path: /metadata/namespace
        value: flux-system
      - op: add
        path: /spec/interval
        value: 24h
      - op: add
        path: /spec/timeout
        value: 1m
  - target:
      group: source.toolkit.fluxcd.io
      kind: GitRepository
    patch: |
      - op: add
        path: /metadata/namespace
        value: flux-system
      - op: add
        path: /spec/interval
        value: 24h
      - op: add
        path: /spec/timeout
        value: 1m
  - target:
      group: source.toolkit.fluxcd.io
      kind: HelmChart
    patch: |
      - op: add
        path: /metadata/namespace
        value: flux-system
      - op: add
        path: /spec/interval
        value: 24h
