apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: proxmox-ccm-proxmox-cloud-controller-manager
    namespace: kube-system
    files:
      - config.yaml=promox-ccm.yaml
  - name: proxmox-csi-proxmox-csi-plugin
    namespace: kube-system
    files:
      - config.yaml=promox-csi.yaml
  - name: cloudflare-api-token
    namespace: manager
    envs:
      - cf-dns-token.env
  - name: cloudflared-cloudflare-tunnel-remote
    namespace: external
    envs:
      - cf-tunnel-token.env
  - name: vaultwarden-admin-token
    namespace: service
    envs:
      - vaultwarden-admin-token.env
  - name: garage-admin-token
    namespace: database
    envs:
      - garage-admin-token.env
  - name: authentik-mainkey
    namespace: service
    envs:
      - authentik-mainkey.env
  - name: n8n-key
    namespace: service
    envs:
      - n8n-key.env
